### ISSUE TITLE
New issues after upgrading to 0.9

### ISSUE THREAD

**Issue by deblasioluca** [inUtil-info/whin2-contrib#7] opened 2023-01-18 15:14 UTC
It seems, the switch button to activate and deactivate the connection does not properly work.

Working:
The button works in order to activate the node receiver in the case when
- the switch is on deactive
- no message sent/received within 1 min
- no new deployment within 1 min

In any other case, the receiver button throws errors continuously as explained in my previous issue report
- Sending / receiving message and deactivating/activating node receiver within 1 min -> continuous errors in log
- Sending / receiving message and deploying -> receiver node will not be in listening mode, therefore requires deactivating / activating -> continous error in log

Deactivating the receiver node when the continous error messages are thrown, does not help. Node red needs to be restarted to stop error messages!

N.B. I'm a subscribed user on RapidAPI, so the node receiver should work for me.

**Comment by lu4t** [comment] 2023-01-18 15:42
Would you mind to paste the logs you get on node-red?. Did some tests and cannot reproduce the error.

Thanks.

**Comment by deblasioluca** [comment] 2023-01-18 15:43
Hi!

Absolutely! Can you guide me how to get the logs you need?

**Comment by lu4t** [comment] 2023-01-18 15:44
if running on docker, just run on a terminal:
docker logs node-red-docker
I guess it's not needed, but just in case: node-red-docker is the name of you node-red container :)

**Comment by deblasioluca** [comment] 2023-01-18 15:50
I’ve installed on Raspberry PI natively. 

I used journalctl to produce below log. Does it help? 

Steps to reproduce:

- used send note to send message
- deactivated receiver node with new switch you’ve implemented
- activated receiver node with new switch you’ve implemented

Above steps within 1 min after sending the message with the sender node

I’ve a Pro subscription (240 messages / day, 1 request per minute)


(node:3068) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at ***@***.***/node-red-whin-whatsapp/whin.js:188:28
    at WhinReceive._inputCallback ***@***.***/node-red-whin-whatsapp/whin.js:192:21)
    at ***@***.***/runtime/lib/nodes/Node.js:210:26
    at Object.trigger ***@***.***/util/lib/hooks.js:166:13)
    at WhinReceive.Node._emitInput ***@***.***/runtime/lib/nodes/Node.js:202:11)
    at WhinReceive.Node.emit ***@***.***/runtime/lib/nodes/Node.js:186:25)
    at WhinReceive.Node.receive ***@***.***/runtime/lib/nodes/Node.js:485:10)
    at ***@***.***/node-red-whin-whatsapp/whin.js:342:18
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at ***@***.***/editor-api/lib/auth/index.js:75:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
(node:3068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 191)
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:17 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died
18 Jan 16:46:18 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN-Error] Unexpected server response: 401
18 Jan 16:46:18 - [warn] [whin_receive:02807b1acc60f4c2] [WHIN] Connection died

**Comment by lu4t** [comment] 2023-01-18 15:54
can you please place a debug node after whin-recive, and confirm if you see a message saying: `"[WHIN] Connection closed cleanly, code=1005 reason="` when you switch from on to off?

**Comment by deblasioluca** [comment] 2023-01-18 16:02
Yes, I do receive the message when switching from ON to OFF. But, if I have the node receiver active and need to restart node red, the button is in a non listening mode but the switch is still on status ON. When I then switch OFF, no message. Followed by the continuous errors once I switch it ON again.

**Comment by lu4t** [comment] 2023-01-18 16:04
Can you confirm if the error does NOT happen if you repeat the process, but wait for more than 1 minute?

**Comment by deblasioluca** [comment] 2023-01-18 16:12
Yes, I can confirm that.

**Comment by lu4t** [comment] 2023-01-18 16:14
Ok, then the code is correctly running,... the problem is the rate limit set on the api gateway (for your plan is 1 Req/min).
I will discuss this setting later today with the Ops team, and see if we can raise the Req/min limit for the PRO plan. 
Until I have feedback, I will leave this issue open.

**Comment by deblasioluca** [comment] 2023-01-18 16:16
Hmm… or would it make sense you have a delay for 1 min to execute the activation with a counter as status message below the node receiver indicating the remaining waiting time?

**Comment by lu4t** [comment] 2023-01-18 16:19
there are some options, and the implications are not obvious. I will get back later today after the meeting...
Just try not to click the switch too quickly :)

**Comment by deblasioluca** [comment] 2023-01-18 16:20
No worries..

**Comment by lu4t** [comment] 2023-01-18 19:13
Rate Limits on the paid plans has been raised to:
PRO 4/min
ULTRA 10/min
MEGA 14/min

You will still be rate limited, but this is as much as I could get out of the Ops team.

I am closing this issue, as there's no bug. Probably it's a Feature that we should add to the nodes roadmap.

**Comment by deblasioluca** [comment] 2023-01-18 19:18
Many thanks for your efforts! Highly appreciated!

**Comment by deblasioluca** [comment] 2023-01-19 08:31
One more observation with the new switch you’ve implemented:

- Node receiver is active and working (it shows the “listening to WhatsApp”)
- Deploy any new changes in node red

—> receiver node stays with active switch, but does not show “listening to WhatsApp” and also does not receive messages. I need to deactivate the node receiver with the switch and activate it again.

**Comment by lu4t** [comment] 2023-01-19 21:43
please update to 0.1.0 to correct the errors (kind of). 

Now the connection will not drop if you do a `only modified flows` or `only modified nodes`. It will drop, and you will need to reconnect, if you do a `full deploy` or a `restart all flows`.

Thanks for the help to address them.

**Closed as completed by lu4t** 2023-01-19 21:43 UTC
